export const initTasklist = [
    {
        "id": "02",
        "TASK": "Assessment Lead",
        "CODE": "2L",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "09",
        "TASK": "PSP Lead",
        "CODE": "1L",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "18",
        "TASK": "Cutting Lead",
        "CODE": "5L",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "01",
        "TASK": "Admin",
        "CODE": "AD",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "07",
        "TASK": "Exurco Operator A",
        "CODE": "4O",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "08",
        "TASK": "Exurco Operator B",
        "CODE": "4O",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "06",
        "TASK": "Exurco Circulator",
        "CODE": "4C",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "04",
        "TASK": "Scalpel Operator A",
        "CODE": "2O",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "03",
        "TASK": "Scalpel Circulator",
        "CODE": "2C",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "19",
        "TASK": "Cutting Circulator A",
        "CODE": "5C",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "20",
        "TASK": "Cutting Operator A",
        "CODE": "5O",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "21",
        "TASK": "Cutting Operator B",
        "CODE": "5O",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "22",
        "TASK": "Cutting Circulator B",
        "CODE": "5C",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "23",
        "TASK": "Cutting Operator C",
        "CODE": "5O",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "11",
        "TASK": "Snapping Operator A",
        "CODE": "1S",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "12",
        "TASK": "Snapping Operator B",
        "CODE": "1S",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "13",
        "TASK": "Snapping Operator C",
        "CODE": "1S",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "14",
        "TASK": "Plucking Operator A",
        "CODE": "1P",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "15",
        "TASK": "Plucking Operator B",
        "CODE": "1P",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "10",
        "TASK": "Snapping Circulator",
        "CODE": "1S",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "05",
        "TASK": "Scalpel Operator B",
        "CODE": "2O",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "16",
        "TASK": "Plucking Operator C",
        "CODE": "1P",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "17",
        "TASK": "Plucking Operator D",
        "CODE": "1P",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    },
    {
        "id": "24",
        "TASK": "Cutting Operator D",
        "CODE": "5O",
        "A1": "",
        "A2": "",
        "B1": "",
        "B2": "",
        "C1": "",
        "C2": "",
        "D1": "",
        "D2": ""
    }
]